apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-passthru-app
  labels:
    app.kubernetes.io/name: wm-passthru-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: wm-passthru-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wm-passthru-app
    spec:
      containers:
        - name: wm-passthru-app-container
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: wm-config
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                    name: wm-api
                    key: NODE_ENV
      restartPolicy: Always
