apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-passthru-app
  labels:
    app.kubernetes.io/name: wm-passthru-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: wm-passthru-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wm-passthru-app
    spec:
      containers:
        - name: wm-passthru-app-container
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: wm-config
          env:
            - name: AUTH_STRING
              valueFrom:
                secretKeyRef:
                    name: wm-passthru
                    key: AUTH_STRING
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                    name: wm-passthru
                    key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                    name: wm-passthru
                    key: CLIENT_SECRET
            - name: CLAMD_HOST
              valueFrom:
                secretKeyRef:
                    name: wm-passthru
                    key: CLAMD_HOST
            - name: CLAMD_PORT
              valueFrom:
                secretKeyRef:
                    name: wm-passthru
                    key: CLAMD_PORT
            - name: CA_CERT
              valueFrom:
                secretKeyRef:
                    name: mutual-authentication-mtls
                    key: CA_CERT
            - name: SERVER_CERT
              valueFrom:
                secretKeyRef:
                    name: mutual-authentication-mtls
                    key: SERVER_CERT
            - name: SERVER_KEY
              valueFrom:
                secretKeyRef:
                    name: mutual-authentication-mtls
                    key: SERVER_KEY
            - name: WM_APP_LABEL
              value: {{ .Values.wmAppBuildLabel.version }}
            - name: WM_APP_ENV
              value: {{ .Values.wmAppEnv }}
      restartPolicy: Always
