apiVersion: v1
kind: ConfigMap
metadata:
  name: wm-config
data:
  WM_APP_LABEL: {{ .Values.wmAppBuildLabel.version }}
  WM_APP_ENV: {{ .Values.wmAppEnv }}
  AUTH_STRING: {{ .Values.auth }}
  SUBMIT_ATTACHMENT_ENDPOINT: {{ .Values.endpoints.submitAttachment }}
  CASELOAD_ENDPOINT: {{ .Values.endpoints.caseload }}
  ENTITY_DETAILS_ENDPOINT: {{ .Values.endpoints.entityDetails }}
  GET_NOTES_ENDPOINT: {{ .Values.endpoints.getNotes }}
  SUBMIT_NOTES_KKCFS_ENDPOINT: {{ .Values.endpoints.submitNotesKKCFS }}
  SUBMIT_NOTES_VISITZ_ENDPOINT: {{ .Values.endpoints.submitNotesVisitz }}
  SUBMIT_SAFETY_ASSESSMENT_ENDPOINT: {{ .Values.endpoints.submitSafetyAssessment }}
