replicaCount: 1
 
image:
  repository: ghcr.io/bcgov/mcfd-mobility-webmethods-passthru
  tag: '<set by CI/CD>'
  pullPolicy: Always
 
service:
  type: ClusterIP
  port: 80
  containerPort: 3200
 
resources: {}
 
nodeSelector: {}
 
tolerations: []
 
affinity: {}

wmAppEnv: '<set by CI/CD>'

aps:
  namespace: '<set by CI/CD>'

wmAppBuildLabel:
  version: '<set by CI/CD>'

auth: '<set by CI/CD>'

endpoints:
  submitAttachment: '<set by CI/CD>'
  caseload: '<set by CI/CD>'
  entityDetails: '<set by CI/CD>'
  getNotes: '<set by CI/CD>'
  submitNotesKKCFS: '<set by CI/CD>'
  submitNotesVisitz: '<set by CI/CD>'
  submitSafetyAssessment: '<set by CI/CD>'

