env:
  - name: NODE_ENV
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: NODE_ENV
  - name: RECORD_CACHE_MS
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: RECORD_CACHE_MS
  - name: CASELOAD_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASELOAD_ENDPOINT
  - name: ENTITY_DETAILS_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: ENTITY_DETAILS_ENDPOINT
  - name: GET_NOTES_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: GET_NOTES_ENDPOINT
  - name: SUBMIT_ATTACHMENT_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SUBMIT_ATTACHMENT_ENDPOINT
  - name: SUBMIT_NOTES_KKCFS_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SUBMIT_NOTES_KKCFS_ENDPOINT
  - name: SUBMIT_NOTES_VISITZ_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SUBMIT_NOTES_VISITZ_ENDPOINT
  - name: SUBMIT_SAFETY_ASSESSMENT_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SUBMIT_SAFETY_ASSESSMENT_ENDPOINT
  - name: CASE_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASE_ENDPOINT
  - name: INCIDENT_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: INCIDENT_ENDPOINT
  - name: SR_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SR_ENDPOINT
  - name: MEMO_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MEMO_ENDPOINT
  - name: ACCESS_TOKEN_URL
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: ACCESS_TOKEN_URL
  - name: CASE_WORKSPACE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASE_WORKSPACE
  - name: INCIDENT_WORKSPACE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: INCIDENT_WORKSPACE
  - name: SR_WORKSPACE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SR_WORKSPACE
  - name: MEMO_WORKSPACE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MEMO_WORKSPACE
  - name: CASE_ID_FIELDNAME
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASE_ID_FIELDNAME
  - name: INCIDENT_ID_FIELDNAME
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: INCIDENT_ID_FIELDNAME
  - name: SR_ID_FIELDNAME
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SR_ID_FIELDNAME
  - name: MEMO_ID_FIELDNAME
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MEMO_ID_FIELDNAME
  - name: CASE_SEARCHSPEC_IDIR_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASE_SEARCHSPEC_IDIR_FIELD
  - name: INCIDENT_SEARCHSPEC_IDIR_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: INCIDENT_SEARCHSPEC_IDIR_FIELD
  - name: SR_SEARCHSPEC_IDIR_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SR_SEARCHSPEC_IDIR_FIELD
  - name: MEMO_SEARCHSPEC_IDIR_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MEMO_SEARCHSPEC_IDIR_FIELD
  - name: EMPLOYEE_ENDPOINT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: EMPLOYEE_ENDPOINT
  - name: EMPLOYEE_WORKSPACE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: EMPLOYEE_WORKSPACE
  - name: MAX_FILE_SIZE_BYTES
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MAX_FILE_SIZE_BYTES
  - name: BODY_SIZE_LIMIT
    valueFrom:
    configMapKeyRef:
        name: wm-config
        key: BODY_SIZE_LIMIT
  - name: CLAM_DEBUG_MODE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CLAM_DEBUG_MODE
  - name: CLAMD_TIMEOUT
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CLAMD_TIMEOUT
  - name: CLAMD_CONFIG_FILE
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CLAMD_CONFIG_FILE
  - name: CLAMD_MULTI_SCAN
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CLAMD_MULTI_SCAN
  - name: CLAMD_BYPASS_TEST
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CLAMD_BYPASS_TEST
  - name: DATA_API_URL
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: DATA_API_URL
  - name: WORKFLOW_API_URL
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: WORKFLOW_API_URL
  - name: AUTH_STRING
    valueFrom:
      secretKeyRef:
          name: wm-passthru
          key: AUTH_STRING
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
          name: wm-passthru
          key: CLIENT_ID
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
          name: wm-passthru
          key: CLIENT_SECRET
  - name: CLAMD_HOST
    valueFrom:
      secretKeyRef:
          name: wm-passthru
          key: CLAMD_HOST
  - name: CLAMD_PORT
    valueFrom:
      secretKeyRef:
          name: wm-passthru
          key: CLAMD_PORT
  - name: CA_CERT
    valueFrom:
      secretKeyRef:
          name: mutual-authentication-mtls
          key: CA_CERT
  - name: SERVER_CERT
    valueFrom:
      secretKeyRef:
          name: mutual-authentication-mtls
          key: SERVER_CERT
  - name: SERVER_KEY
    valueFrom:
      secretKeyRef:
          name: mutual-authentication-mtls
          key: SERVER_KEY
  - name: CASE_RESTRICTED_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASE_RESTRICTED_FIELD
  - name: CASE_STATUS_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: CASE_STATUS_FIELD
  - name: INCIDENT_RESTRICTED_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: INCIDENT_RESTRICTED_FIELD
  - name: INCIDENT_STATUS_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: INCIDENT_STATUS_FIELD
  - name: SR_RESTRICTED_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SR_RESTRICTED_FIELD
  - name: SR_STATUS_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: SR_STATUS_FIELD
  - name: MEMO_RESTRICTED_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MEMO_RESTRICTED_FIELD
  - name: MEMO_STATUS_FIELD
    valueFrom:
      configMapKeyRef:
          name: wm-config
          key: MEMO_STATUS_FIELD
